### ISSUE TITLE
Add Filtering of Resources

### ISSUE THREAD

**Issue by lebogg** [clouditor/new-ui#14]
# Problem
A CSP may want to filter the resources that are being assessed, e.g. only show only PROD resources. Therefore it would be nice to have a filtering option in the UI to do this.
For now, I can think of the following approaches a CSP can filter its resources (Azure terminology):

```[tasklist]
### Tasks
- [x] Per Resource group
- [x] Per Tagging
- [x] Per Naming (e.g., "PROD_myAwesomeVM")
- [ ] Combination of these
- [ ] (Per subscription. But I think the CL engine only can handle one subscription at a time)
```

# Solution
Add filtering option. I guess it should be at the level of cloud service configuration if we have this already
